version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./meu_site:/usr/share/nginx/html
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: meu_banco_de_dados
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
